### ISSUE TITLE
Аффтар - Извращениц!

### ISSUE THREAD

**Issue by EvilBeaver** [san-smith/USSRHTML#3]
Не знаю, как должен разрешиться этот issue :)

Может галоперидол или на пивко скинуться?

**Comment by san-smith** [comment]
Вообще, мотивы происхождения этого проекта описаны в статье на Хабре: https://habr.com/post/309552/
Но если вы скинетесь на пивко, я тоже буду рад:)

**Comment by EvilBeaver** [comment]
В данном случае, "извращениц" - это комплимент )
